const dataIkan = [
  {
    iid: "dbm",
    nama: "Discus Blue Mercury",
    ukuran: ["2.5 inch", "3 inch"],
    makanan: ["Pelet", "Kutu air", "Artemia", "Cacing sutra"],
    harga: [150000, 305000],
    gambar: "gambar/ikan/discus blue mercury.jpg",
    stok: [12, 7],
  },
  {
    iid: "cs",
    nama: "Caviat Silver",
    ukuran: ["5cm"],
    makanan: ["Kutu", "Pelet"],
    harga: [9500],
    gambar: "gambar/ikan/caviat silver.jpg",
    stok: [120],
  },
  {
    iid: "sl",
    nama: "Sepat Lalius",
    ukuran: ["4-5cm"],
    makanan: ["Pelet"],
    harga: [12500],
    gambar: "gambar/ikan/sepat lalius.jpg",
    stok: [6],
  },
  {
    iid: "rtc",
    nama: "Red Tail Catfish",
    ukuran: ["6-7cm"],
    makanan: ["Pelet"],
    harga: [39000],
    gambar: "gambar/ikan/red tail catfish.jpg",
    stok: [34],
  },
  {
    iid: "bkk",
    nama: "Baby Koi Kabuto",
    ukuran: ["6-7cm"],
    makanan: ["Pelet"],
    harga: [15000],
    gambar: "gambar/ikan/baby koi kabuto.jpg",
    stok: [9],
  },
  {
    iid: "dlr",
    nama: "Discus Leopard Ring",
    ukuran: ["2.5 inch", "3 inch", "3.5 inch", "4 inch", "4.5inch"],
    makanan: ["Pelet", "Kutu air", "Artemia", "Cacing sutra"],
    harga: [220000, 300000, 405000, 750000, 950000],
    gambar: "gambar/ikan/discus leopard ring.jpg",
    stok: [2, 6, 3, 7, 2],
  },
  {
    iid: "dwp",
    nama: "Discus White Pigeons",
    ukuran: ["2 inch", "2.5 inch", "3 inch"],
    makanan: ["Pelet", "Kutu air", "Artemia", "Cacing sutra"],
    harga: [65000, 147000, 300000],
    gambar: "gambar/ikan/discus white pigeon.jpg",
    stok: [5, 8, 12],
  },
  {
    iid: "dm",
    nama: "Discus Mozaik",
    ukuran: ["2 inch", "1 inch"],
    makanan: ["Pelet", "Kutu air", "Artemia", "Cacing sutra"],
    harga: [120000, 200000],
    gambar: "gambar/ikan/discus mozaik.jpg",
    stok: [2, 2],
  },
];

const dataKeperluan = [
  {
    uid: "plt-gs",
    nama: "Pelet Growth Sinking",
    harga: 45000,
    gambar: "gambar/keperluan/growth-sink.jpg",
    stok: 3,
    keterangan: "Berat 100gram, cocok untuk ikan diskus",
  },
  {
    uid: "plt-cs",
    nama: "Pelet Color Sinking",
    harga: 55000,
    gambar: "gambar/keperluan/color-sink.jpg",
    stok: 2,
    keterangan: "Berat 100gram, cocok untuk ikan diskus",
  },
  {
    uid: "obat-rexternal",
    nama: "Royal External",
    harga: 15000,
    gambar: "gambar/keperluan/rexternal.jpg",
    stok: 12,
    keterangan:
      "isi 10ml obat anti jamur, bakteri dan parasit. Yang di formulasi kan untuk pencegahan,dan juga penyembuhan.",
  },
  {
    uid: "obat-garamikan",
    nama: "Garam Ikan",
    harga: 5000,
    gambar: "gambar/keperluan/garam ikan.jpg",
    stok: 12,
    keterangan:
      "garam ikan atau garam murni tanpa msg. untuk pengobatan dan pencegahan sakit pasangan hias 2 sendok makan per 100 liter pengobatan 1 sendok makan per 100 liter untuk relaxasi ikan",
  },
];
